//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int Item_Id { get; set; }
        public int List_Id { get; set; }
        public string Item_Name { get; set; }
        public int Quantity { get; set; }
        public string Category { get; set; }
        public string IsBought { get; set; }
        public decimal Estimated_Price { get; set; }
    
        public virtual ShoppingList ShoppingList { get; set; }
    }
}
