//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SharedList
    {
        public int Share_Id { get; set; }
        public int List_Id { get; set; }
        public int Shared_User_Id { get; set; }
    
        public virtual ShoppingList ShoppingList { get; set; }
        public virtual User User { get; set; }
    }
}
