//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingList
    {
        public ShoppingList()
        {
            this.Items = new HashSet<Item>();
            this.SharedLists = new HashSet<SharedList>();
        }
    
        public int List_Id { get; set; }
        public int User_Id { get; set; }
        public string List_Name { get; set; }
        public System.DateTime C_Date { get; set; }
    
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<SharedList> SharedLists { get; set; }
        public virtual User User { get; set; }
    }
}
