//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSysMngmt.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Like
    {
        public int like_id { get; set; }
        public int user_id { get; set; }
        public int post_id { get; set; }
        public int flags { get; set; }
        public int count { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual User User { get; set; }
    }
}
