//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSysMngmt.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Comments = new HashSet<Comment>();
            this.Likes = new HashSet<Like>();
            this.PostTags = new HashSet<PostTag>();
        }
    
        public int post_id { get; set; }
        public int user_id { get; set; }
        public string title { get; set; }
        public string p_content { get; set; }
        public System.DateTime pub_date { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Like> Likes { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<PostTag> PostTags { get; set; }
    }
}
