//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSysMngmt.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.PostTags = new HashSet<PostTag>();
        }
    
        public int tag_id { get; set; }
        public string tag_name { get; set; }
    
        public virtual ICollection<PostTag> PostTags { get; set; }
    }
}
