//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogSysMngmt.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int profile_id { get; set; }
        public int user_id { get; set; }
        public string fullname { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string education { get; set; }
        public string gender { get; set; }
        public string hobbies { get; set; }
        public string social_link { get; set; }
        public string img_name { get; set; }
    
        public virtual User User { get; set; }
    }
}
